[package]
name = "interview-cake"
version = "0.1.0"
authors = ["Darren Tsung <darren@onesignal.com>"]
edition = "2018"

[dependencies]
ego-tree = "0.6.2"
ego-binary-tree = "0.1.0"
# ego-binary-tree = { path = "../ego-binary-tree" }
